# Generated by Django 6.0.3 on 2026-03-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsession',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnsession',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vpnsession',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
