# Generated by Django 6.0.3 on 2026-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_vpnsession_country_vpnsession_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnsession',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vpnsession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
