# Generated by Django 6.0.3 on 2026-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_alter_vpnsession_country_alter_vpnsession_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnsession',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
