# Generated by Django 6.0.3 on 2026-03-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_vpnsession_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiGateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('api_token', models.CharField(max_length=255)),
                ('poll_interval', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
