# Generated by Django 6.0.3 on 2026-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_fortigateconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortigateconfig',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fortigateconfig',
            name='port',
            field=models.IntegerField(default=443),
        ),
    ]
