# Generated by Django 6.0.3 on 2026-03-07 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_remove_fortigateconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortigateconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpnsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpnsession',
            name='vpn_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vpnsession',
            index=models.Index(fields=['username'], name='vpn_vpnsess_usernam_dd8759_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnsession',
            index=models.Index(fields=['connected_at'], name='vpn_vpnsess_connect_2918d9_idx'),
        ),
    ]
